<div id="homepagearticle1">
<div>
Why this website? <br><br>
This website was the brainchild of Lucio Daniele Franco&sbquo; Don Miller&rsquo;s grandson&sbquo; who wanted to pay tribute to the only grandfather he knew and to build his website design skills. But it is also the collective effort of many individuals: Don&rsquo;s wife, his children and grandchidren&sbquo; his colleagues and his friends. <br><br> 
This website offers us all an opportunity to collect and appreciate his accomplishments&sbquo; and share the experiences and love that we feel for Don Miller - husband&sbquo; father&sbquo; grandfather&sbquo; scientist&sbquo; activist&sbquo; elected politician&sbquo; musician and music lover&sbquo; Jew&sbquo; environmentalist&sbquo; and friend. This site belongs to all those who knew him. To quote Kahil Gibran &quot;To live in the heart of those we leave behind is not to die&quot; -- Donald G. Miller&sbquo; we will never forget you. <br><br> 
We invite you to browse through the various pages of this site&sbquo; remember the sides to Don Miller that you knew&sbquo; and discover other sides to him that perhaps you did not know. <br><br><hr />
</div>
<p><img src="images/cover.jpg" alt="cover.jpeg" width="116" height="171" style="padding-left:20px;padding-right:20px;float:right;">
<i>Donald G. Miller</i> was a many-faceted man. A highly respected scientist, his work in  physical chemistry was known around the world.  He was a life-long civic activist, whose 50 years of determined  participation in local politics had significant impacts on life in  Livermore and the Livermore Valley. He  was a founding member of and an active participant in Congregation Beth Emek. He authored 174 papers. His  interests ranged from ragtime and classical music to shooting and  ballistics. And, he was both loved and highly  respected by his family and multitude of friends.<br />
  </p>
<p>Born and raised in Oakland, California, he spent all but 8  of his 84 years in the Bay Area. He  graduated from the University of California, Berkeley in 1949, with a B.S. with  honors in chemistry and earned his Ph.D. from the University of Illinois,  Urbana-Champaign in 1952. He spent most  of his scientific career as a research chemist at the Lawrence Livermore  National Laboratory. He was awarded a  Fulbright Fellowship in 1960-61, spending the school year teaching at two  universities in Lille, France. He also  taught at a number of universities around the world over the course of his  life.<br /><br />
  Livermore&rsquo;s numerous parks, undeveloped hillsides,  fountains, charming downtown with cultural spaces, and lack of distracting  signs are just a few of the testimonials to Donald Miller&rsquo;s civic  activism. He fought against unlimited development, seeking to protect the area&rsquo;s air, water, open space and natural  beauty.</p>
</div>