<p><b>Tribute by Nancy Miller&sbquo; Daughter</b></p>
<p>There are many&sbquo; many things that could be said about my father. If we said all of them&sbquo; we would be here for a very long time. Instead&sbquo; a few speakers will be talking about particular parts of Dad&rsquo;s live and work – his political life&sbquo; his scientific life and his overall contributions to the Valley. I am going to try to put a bit of a frame around it.<br><br>

Dad lived by the saying from the Pirke Avot (Sayings of the Fathers) that you are not required to complete the work of life&sbquo; but neither may you desist from it. In his case&sbquo; he saw that as Tikkun Olam&sbquo; repairing the world. He found the areas where he thought he could help&sbquo; where he could make a difference&sbquo; and he spent his life working at those. And&sbquo; the world&sbquo; particularly his corners of it&sbquo; are very much better for his having been here.<br><br> 

He was a man of contrasts. He was a straight shooter. And a rifle shooter. Die-hard liberal. Life member of the NRA. Cynical. Musical. Hilarious. Curious. Hard-nosed. Thoughtful. Scientist. Humanist. Quick to anger. Even quicker to forget that there was anything to be angry about. Seeing the world in black and white. But seeing most people in shades of gray. Focused. Persistant. Distractible. And&sbquo; among the 174 publications he had during his lifetime&sbquo; he is the only person&sbquo; I am sure&sbquo; who in the same year&sbquo; published papers in the Journal of Physical Chemistry and in Varmint Hunter. And&sbquo; he was an incredible role model.<br><br>

Every family has its &quot;phrases from our childhood.&quot; My sister and I put many of them together in a book that we gave to dad on his 50th birthday&sbquo; and added to for his 60th&sbquo; and 70th. Dad&sbquo; being a creature of habit&sbquo; never stopped using the old phrases. But the key ones had to do with our obligations to our family and our community. We had a duty to do the right thing&sbquo; and to &quot;do unto others as they would be done to.&quot; The part about &quot;as they would be done to&quot; as opposed to the more common &quot;as we would like someone to do for us&sbquo;&quot; was a critical distinction for him. It wasn&rsquo;t supposed to be about us&sbquo; but about standing in the other person&rsquo;s shoes. <br><br>

Many people here know about dad&rsquo;s work and achievements in the Livermore Valley. He was an environmentalist before environmentalism was cool. The fact that the ridgelines and hillsides of the Livermore Valley are still open space is one of his many legacies in this area. And&sbquo; I will let others talk about that in more detail. But&sbquo; he had the same devotion to doing the right thing in many other contexts. For example&sbquo; when his brother Stanley had a stroke a dozen years ago&sbquo; and no longer was really able to care for himself&sbquo; dad stepped in. Dad&sbquo; who probably saw his brother once a year&sbquo; and who had never served as a real caregiver&sbquo; stepped in. He devoted hours and hours over the next eight years to making sure that Stanley had what he needed&sbquo; that he was being well-taken care of&sbquo; that his finances were in shape&sbquo; that his legacy (because he was an extremely prominent scientist) was protected. And&sbquo; none of those tasks were the type of thing that dad&sbquo; given his &quot;druthers&sbquo;&quot; would do for himself. But&sbquo; he did it for his brother&sbquo; because blood is always thicker than water&sbquo; and it was the right thing to do.<br><br>

My dad was not the &quot;rose-colored glasses&quot; type. &quot;Cynicism and pessimism are the only true guides to reality&quot; was one of the Sayings of Don Miller. He didn&rsquo;t expect to win all (or even hardly any) of his fights&sbquo; but that rarely kept him from fighting anyway. So long as you MIGHT be able to do something positive&sbquo; you have a duty to do it. That the Livermore Valley doesn&rsquo;t look like Los Angeles is testament to his lifelong efforts. But it is also testament to his ability to convince lots of others that things he cared about were important. He always understood that it took more than one person to win a battle&sbquo; and that credit had to be shared. But&sbquo; he was also willing to be on the short end of a 4-1 vote of the city council to make his point&sbquo; and to remain true to his principles.<br><br>
 
He was totally honest. I never saw him cheat&sbquo; even at poker&sbquo; which he taught us as young kids. I never saw him try to get out of paying for something. He was scrupulous in making sure that he took leave for any city or personal business activity during the work day. (As a result&sbquo; we didn&rsquo;t have much in the way of family vacations while he was on the city council.) He never had to say &quot;do as I say&sbquo; not as I do.&quot;<br><br>

As I noted&sbquo; he was a Life Member of the NRA. And&sbquo; I don&rsquo;t know how many hours we spent disputing issues relating to the Second Amendment. But&sbquo; he derived his views about the importance of citizens having access to guns without registration from Jewish history; if the government knows where all the guns are&sbquo; there is no way to have a resistance against tyrants. And&sbquo; while I don&rsquo;t completely agree with his views on gun control&sbquo; there was (as there always was for him) a principle behind it.<br><br>

And&sbquo; he focused his interest in guns primarily on the science of them -- ballistics. He published 37 articles&sbquo; in publications as varied as Precision Shooting&sbquo; Black Powder Cartridge News&sbquo; and my personal favorite -- Varmint Hunter. Some were highly technical and were peer-reviewed&sbquo; but many were aimed at a much more lay audience. <br><br>

One of the things he particularly enjoyed about ballistics was that it introduced him to a whole different world of readers and colleagues. And&sbquo; the accolades that have come in from people in the ballistics world have been amazing&sbquo; particularly related to the &quot;twist&quot; rule. But probably the part that was the most important to him was that it was something he was able to share with his grandson Lucio.<br><br>

He loved music. He played the piano and the harpsichord. He wrote three pieces of rag time. And I remember falling asleep as a child to the sound of his playing the piano in the living room. It was usually Bach (or ragtime) and it meant to me that I was safe because Dad was there&sbquo; live&sbquo; in the living room.<br><br>

But he also took his interest in music&sbquo; and made Livermore and the valley a better place&sbquo; by his 30 years of work with Del Valle Fine Arts and the Cultural Arts Commission. Again&sbquo; it wasn&rsquo;t enough that he loved music and enjoyed it himself. He worked to make sure that others in the community had the same opportunities. He worked avidly for the Bankhead Theatre. And&sbquo; when a few years ago&sbquo; a magazine listed Livermore as one of the best places to live&sbquo; the cultural and intellectual activities in town were part of the reason.<br><br>

Although Dad had strong views about many things (okay -- most things)&sbquo; particularly as he got older&sbquo; he didn&rsquo;t demonize his opponents. He was certainly &quot;hard-nosed&sbquo;&quot; or as he sometimes described himself&sbquo; a &quot;pig head&sbquo;&quot; but he could be tremendously personally gracious. With perhaps the exception of &quot;the developers&quot; and those he saw as the enemies of Israel&sbquo; he would often say about the people who didn&rsquo;t see things his way that &quot;their heart is in the right place.&quot; <br><br>

Dad and my husband Ralph were great friends. And when Mom and Dad spent time in Washington DC&sbquo; the two of them frequently had what Mom and I called &quot;boys&rsquo; movie night.&quot; They would eat popcorn and watch old westerns&sbquo; suspense thrillers and other truly &quot;wonderful&quot; movies. But the title of the last movie they watched together&sbquo; just about week ago&sbquo; is a wonderful description of my dad. They watched the original &quot;True Grit.&quot</p>