<p><b>Tribute by Susan Rodriguez, Niece</b></p>
<p>My name is Susan Rodriguez. I&rsquo;m Don&rsquo;s niece by marriage. Thinking back, I realize I&rsquo;ve always thought of Uncle Don as a blood relative. He was just that kind of person who loved his family dearly and treated each of us so specially. 

I had the privilege of accompanying Uncle Don and Aunt Miriam to some of the medical appointments at which Don was gathering the information he needed to come to terms with his new cancer diagnosis. While in the midst of the agonizing process of deciding whether he would undergo radiation and/or some other type of treatment, Don pulled me aside to tell me that me there were three things for which he hoped he would be remembered: his contributions to physical chemistry, his contributions to music, and his contributions to ballistics. He explained to me that he had unfinished business in each of these areas, and that he would make his decision about further treatment based on the implications of that decision for his ability to ensure that the contributions that were important to him were completed. Given my research science background, Don was sure I&rsquo;d understand the urgency he felt in getting what he saw as these loose ends tied up. I&rsquo;d like to share my thoughts on these contributions that Don wanted to make in the context of the contributions I believe he actually made to my life and to the lives of his family.<br />
<br/>

Let&rsquo;s start first with Don&rsquo;s contributions to physical chemistry, a field of which I must say I have at most the barest comprehension. Don clearly will be well remembered in this field to which he made important contributions and in which he authored many publications. He had research papers he made sure were finished before he died. But what I saw in relation to this professional contribution was an incredible analytical and scientific mind. Time and again, my family and I had in-depth discussions, and often debates, with Don on a wide range of topics pertaining to our work or our interests. Don could always find common ground with each of us. Don clearly thought like a well-trained scientist, and he would listen carefully to the details we would present in order to challenge our statements and enhance his understanding, and at the same time force us to examine and justify our own thinking about what we were saying. I don&rsquo;t think Don ever ran across a verbal challenge he didn&rsquo;t want to take on or a scientific issue or puzzle he didn&rsquo;t want to tackle.<br /><br />

Don wanted to be remembered for his contribution to ragtime music, and it was important to him that the music he&rsquo;d written be scored before he died. What I saw was a person who made sure there was music around him, and who, with Lynne, built a clavichord so he could make the music he loved (this in a person who avoided home repairs whenever possible because fixing things clearly was not his forte. He barely knew what to do with the few tools he had in his garage, if he could even find them). Don wrote wonderful and complex ragtime music. Interestingly, he was able to write this music in the absence of sufficient piano-playing proficiency to be able to play what he&rsquo;d written himself.<br><br>

Don also wanted to be remembered for his contributions to ballistics, and it was important to him that his final ballistics manuscript be completed before he died. What I saw was a person with liberal politics combined with what was, for me, an unfathomable commitment to the second amendment. But what I also saw, in addition to the intensity of his commitment to his right to own guns and shoot them responsibly, was a person who wanted to ensure this passion was passed on to, and cherished by, his grandson. I also saw a person whose contributions to ballistics were, at some level, based on intriguing problems to which he could apply his unique scientific mind and perspective.<br /><br />

Don never missed a chance to tell others that the world was black and white&sbquo; good guys versus bad guys (bad guys frequently were referred to by him as turkeys). Don fought hard for the things he so firmly believed in – the city of Livermore&sbquo; the need to control the growth of Pleasanton and the 580 corridor. But despite this professed good guy/bad guy dichotomy&sbquo; and despite his willingness to debate anyone on any of these issues at any time&sbquo; Don allowed those of us around him to see shades of grey. And perhaps underneath Don did so as well.<br /><br />

Don enjoyed&sbquo; I believe&sbquo; thinking of himself&sbquo; and being perceived&sbquo; as somewhat of a curmudgeon. However&sbquo; what I saw behind that façade was a man who always&sbquo; always conducted himself with grace and dignity and compassion. Don was a man of strong opinions that were passionately held. He and Miriam even occasionally politely disagreed in my presence. But never did I see Don&rsquo;s strong opinions or his disagreements color his appraisal of the person with whom he was debating. Don did not hold grudges&sbquo; and he could love you just much whether you agreed with him or not.<br /><br />

Don decided to undergo radiation because he had things he wanted to have the time to finish. However&sbquo; I suspect that even if Don had lived another 84 years&sbquo; he would not have come to the end of his To Do List. Don always had more ideas and more things to analyze. But with all of these things he wanted to do&sbquo; what I saw was a person who always had time for every family event and dinner and discussion and request for assistance or someone to just listen. I don&rsquo;t think I ever heard that Don couldn&rsquo;t make a family event because he had other commitments. Don was impatient to get so many things done&sbquo; and he certainly expressed impatience with what the turkeys in this world were doing&sbquo; but what I saw was a very patient person who always gave generously of his time and of himself to those around him.<br /><br />

Don&rsquo;s life in fact was not one of contradictions. Instead&sbquo; it was the multifaceted life of a many faceted and wonderful person. Don will be greatly missed. Please lift a glass of Pepsi&sbquo; or beer&sbquo; to his memory&sbquo; and don&rsquo;t forget to top each dessert with lots of cream&sbquo; whipped hard&sbquo; in his honor.</p>