<p>It seems that for whatever reason I have inadvertently made a habit of collecting rocket scientists and high-end mathematicians and physicists as friends and acquaintances. Often, one of these relationships started when someone wrote or telephoned me to comment on something I had theorized upon in print. Sometimes those comments were entirely positive and sometimes those included constructive criticism, which I always appreciated just as much, or more, as I did the compliments.</p>
<p> </p>
<p>My relationship with Don Miller, your grandfather, began when I discovered his groundbreaking work on estimating blackpowder ballistics, which he based entirely upon the reduction to formulae of data that he found in published sources. Don was acutely aware of the variables inherent in blackpowder component purity, mixture ratios, and particle pulverization (size and uniformity of size; particle mixing; loading techniques; data recording; etc. He explicitly recognized the inherently large error envelope inherent in the predictions of any such formula.</p>
<p> </p>
<p>This is what encouraged me to visit with him. Yes, what he had done was fascinating but what was more critical to me was that he clearly recognized why his formulae could never be used for anything more than wildly approximate predictions.</p>
<p> </p>
<p>That bit of honesty was so in contrast to the typical situation in physics, where someone takes wildly approximated values and applies even more wildly approximated and unjustified simplifications full of unsupported assumptions and comes to a conclusion that he will defend to the death!</p>
<p> </p>
<p>That was not Don Miller; he was not interested in acclaim. He was interested in facts and he was very interested in finding ways for serious shooters to better predict values that matter very much to them (and very little to others). As By Smalley has well noted, Don worked tirelessly to improve upon formulas for estimating needed twist rates for various sporting bullets.</p>
<p> </p>
<p>Let me explain why this was most interesting to me. Historically, we have had two methods of determining needed twist rate: theoretical and practical.</p>
<p> </p>
<p>The theoretical is easy to understand: Take a bunch of wildly generalized formulas that are supposed to represent physical processes that prove to be unrepresentable without wildly unjustified simplifying assumptions and figure out how much destabilizing force is therefore acting upon a bullet in ballistic flight and therefore how much spin rate is required to provide enough stability to result in what we loosely refer to as stable flight — accuracy.</p>
<p> </p>
<p>The practical is easier still to understand: Fire bullets at various velocities from barrels with various twist rates with well-measured atmospheric conditions and look at actual results.</p>
<p> </p>
<p>I have already decried the inherent errors in the theoretical approach, but I can perhaps best clarify the difference in reality and theory in this regard by noting that for the most part in order to get good accuracy we find that we need a barrel with a twist rate that delivers about 150% of the predicted necessary stability factor — that is, we need a twist rate that is about 22% faster than predicted! That, my friends, is a huge error. Where else in physics would we settle for such an error?<br>
		Tributes to Don Miller on Ballistics<br>
</p>
<p>The problem with the theoretical approach is actually worse. What we find is that actual barrel twist often varies significantly from claimed twist, nominally identical bullets vary from lot to lot and otherwise, atmospheric conditions vary while we test and we cannot do a perfect job of tracking that, etc. Worse, it is well recognized that sometimes a bullet fired from the same load will be stable in one gun and not stable in the next gun despite the two guns having identical twists! I know of one test where one gun with a 14-twist would not stabilize a specific bullet fired from a 30-06 but when an otherwise identical 16-twist barrel was installed on that gun the load was accurate! No theory could ever explain that reality.</p>
<p> </p>
<p>Don, looked into this mire of theoretical and actual conundrums and saw clearly through it toward an answer or at least a reasonable approach: His solution was to gather actual field data, plot actual results, and derive a formula that would fit that data. What a novel concept! And, his results will stand the test of time because his formulae are the best to date.</p>
<p> </p>
<p>He was so excited to learn that I had a barrel that short a specific load accurately at 6300 feet elevation at 65 degrees F and with marginal accuracy at 4500 feet and 75 degrees and with no accuracy at 1500 feet and 80 degrees. That hard data made his day, which made my day.<br>
</p>
<p>I could go on but what I started out here to note was that Don was a rare soul who was willing to address a quandary merely for the purpose of understanding and that he held that spirit until the very end of a very productive life. It was my honor to know him, if all too briefly.</p>
<p>--Mic McPherson</p>
<p>Don's work on spin stability of bullets is the best available. By using statistical analysis combined with physical characteristics of the bullet he was able to provide the best predictions for the amount twist necessary to stabilize bullets under all external conditions. He would (and did) go to the end of the earth to dig up data for his analyses. I used to tease him because he independently derived the &quot;drag bucket&quot; (condition of minimum drag) that sometimes occurs when fluid flow changes from turbulent to laminar in aerodynamics at specific Reynolds Numbers. He did this by analyzing the data on the range of cannon balls fired during the 18th and 19th centuries. I can't imagine where he got the data to do that analysis. </p>
<p>-- By Smalley</p>
