<p><b>Tribute by Joan Seppala&sbquo; Publisher of The Independent</b></p>
<p>In the fall of 1963&sbquo; Don Miller propelled himself up the stairs of the Schenone building into The Independent&rsquo;s new office even before our first issue was published. He was a man on a mission. He wanted our editor&sbquo; Dana McGaugh&sbquo; to see the vision early&sbquo; to understand how the Livermore should become a source of intense local pride. Although he is best known for protecting the open hills&sbquo; ranches and vineyards surrounding us&sbquo; he imagined more. Over fifty years&sbquo; he provided passionate leadership for a broad range of beautification and cultural issues that benefit us to this day.<br><br> 
Back in 1961 after returning from a trip to France&sbquo; he thought Livermore should become a city of fountains. He suggested that a fountain be built at the west end of First Street where the road splits and a rose garden is now located. The council bluntly said&sbquo; &quot;No.&quot;  Undeterred&sbquo; he and Jim Day raised $1500 and the fountain was built. Now&sbquo; of course&sbquo; the city has half a dozen.<br><br>
It&rsquo;s little known that it was Don who led the fight to impose a park development fee on development projects to provide community parks throughout the neighborhoods. He was afraid that if people knew that it was his idea&sbquo; they would vote against it. Behind the scenes&sbquo; he went to others who persuaded the planning commission to advance the concept. The strategy worked. As a result&sbquo; we are blessed with an abundance of parks for all of us to enjoy. <br><br>
Don cared about the downtown. He wanted it to be purged of large&sbquo; garish signs that cheapen the character of the community. Thankfully&sbquo; the strict sign ordinance that he authored is still in place.<br><br>
Don looked at our beautiful hills&sbquo; and wanted them preserved. In combination with Jim Day and Jean Rozsnyia&sbquo; he launched the Scenic Corridor referendum in 1982. It passed&sbquo; but that was only the beginning. In proposing their projects&sbquo; developers often wanted to bend the Scenic Corridor rules. At City Council hearings over and over&sbquo; Don stood at the podium to admonish both the developers and the City to follow the letter of the law.<br><br>
Along with allies such as Margaret Tracy and once again&sbquo; Jim Day&sbquo; he founded Citizens for Balanced Growth. Working with the City of Livermore&sbquo; the organization landed $6 million for open space acquisition by suing Dougherty Valley developers on a water issue. The funds are still being used to purchase land in the North Livermore area.<br><br> 
Don worked to build Livermore&rsquo;s cultural riches as tirelessly as he did to protect its aesthetics. In the late 50&rsquo;s&sbquo; he participated in the local theater group&sbquo; Cask and Mask&sbquo; and collaborated in writing satiric pieces for the cast to enjoy at their parties after the performances. After the May School Theater burned down&sbquo; the home of Cask and Mask&sbquo; Don joined others to bring forth a new theater&sbquo; but as he explained&sbquo; the timing was not right. In recent years&sbquo; Don lent financial and political support to the Bankhead Theater&sbquo; and repeatedly stood up for the regional theater at council meetings.<br><br>
Don was also a composer. For the City&rsquo;s Centennial in 1969&sbquo; he wrote the Centennial Rag&sbquo; followed by the Nostalgia Rag in &rsquo;71. My favorite is the Political Rag&sbquo; which he wrote in &rsquo;75 for The Independent newspaper. These rags were his way of celebrating our unique community.<br><br>
Back in 1966&sbquo; he and four others founded the Livermore Cultural Arts Council&sbquo; and served on it until a few years ago. From its early days until a few months before his death&sbquo; he served on the board of Del Valle Fine Arts&sbquo; an organization that brings quality chamber music to Livermore.<br><br>
As Don said a month ago&sbquo; &quot;I have lived my life with gusto.&quot; Indeed he did. Over the last fifty years&sbquo; Livermore became a model City because of the beauty of the vineyards and hills that surround it&sbquo; and the fountains&sbquo; parks and cultural amenities within. How remarkable that one man was the father of all these blessings.<br><br> 
Don lives on in these tangible ways. He also lives on in each of us. I believe that when someone dies who has deeply affected us&sbquo; we carry that person&rsquo;s spirit inside. There it continues and flows out to others. 
May we all honor Don by continuing to celebrate&sbquo; protect and enhance the community that he so passionately loved.</p> 